# Generated by Django 3.0.4 on 2020-04-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='user',
            new_name='username',
        ),
    ]
